### ISSUE TITLE
R1D1[Doc]Разработка концепта текстового редактора команды №3

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#1]
Проблема
---
Требуется разработать концепт текстового редактора, удовлетворяющего потребностям клиента.

Решение
---
Разработать концепт, позволяющий декомпозировать задачу на отдельные модули

Задачи
---
- [x] - разработать вариант концепта;
- [x] - прогнать концепт через ревьюинг команды;
- [x] - выкатить готовое решение.

Информация
---
Предварительный вариант концепта написан Ruslan Kazalakov @Legendary2 (Telegram).
https://docs.google.com/document/d/11IZzY1ydMdF4AkEYR1bV52QHqCVtNBU3/edit

**Comment by Legendary2** [comment]
Ruslan Kazalakov - это если что я.

**Comment by AJIKAIIIMMM** [comment]
Прилагаю свои примечания к концепту. @Legendary2 

[Concept Editor_v1_c_примечаниями_РММ.docx](https://github.com/Legendary2/GB_CommandProgCPP_team3/files/10527498/Concept.Editor_v1_c_._.docx)

**Comment by Legendary2** [comment]
Посмотри в гугл диске, я немного правил в течение последнего часа. Но мне все нравится. Компаньоны наши  пока ничего не вносили. Так что пока все хорошо!

**Comment by Legendary2** [comment]
Возьми за основу наш последний файл из гугла. Который без фамилий(имею ввиду список участников).

**Comment by Legendary2** [comment]
> Прилагаю свои примечания к концепту. @AJIKAIIIMMM
> 
> [Concept Editor_v1_c_примечаниями_РММ.docx](https://github.com/Legendary2/GB_CommandProgCPP_team3/files/10527498/Concept.Editor_v1_c_._.docx)

Предлагаю сделать титульник к нашему концепту. Доработать оглавление, прилизать текст. Если есть идеи по реализации презентации - предлагаю реализовать.

**Comment by Legendary2** [comment]
Предложение: Убрать папку с концептом из репозитория

**Comment by Legendary2** [comment]
Выношу на рассмотрение нового варианта концепта приложения
[Концепт приложения «Графический редактор».docx](https://github.com/Legendary2/GB_CommandProgCPP_team3/files/10557438/default.docx)  @AJIKAIIIMMM

**Comment by Legendary2** [comment]
Удалил папку с концептом

**Comment by Legendary2** [comment]
@v01z предложил несколько правок, в частности - указать год на титульнике, поправить никнейм участника, поменять некоторые выражения.
Все правки внес в документ.

[Концепт приложения «Графический редактор».docx](https://github.com/Legendary2/GB_CommandProgCPP_team3/files/10560633/Concept.docx)

**Comment by Legendary2** [comment]
[Концепт приложения «Графический редактор».docx](https://github.com/Legendary2/GB_CommandProgCPP_team3/files/10560625/Concept.docx)

**Comment by Legendary2** [comment]
Заново выкладываю последнюю правку концепта.
[Concept.docx](https://github.com/Legendary2/GB_CommandProgCPP_team3/files/10560643/Concept.docx)

**Comment by AJIKAIIIMMM** [comment]
https://docs.google.com/document/d/11IZzY1ydMdF4AkEYR1bV52QHqCVtNBU3/edit

Залил документ в наш сток и добавил комментарий. Прошу ознакомиться. @Legendary2

**Comment by Legendary2** [comment]
@AJIKAIIIMMM внес значительные правки. Прошу у команды просмотреть новую версию концепта. Все правки внес в облаке.

**Comment by AJIKAIIIMMM** [comment]
Разработка документа завершена.
