### ISSUE TITLE
R1T0[Dev]Разработка макета приложения для первого релиза

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#10]
Проблема
---
Требуется разработать макет текстового редактора, для унификации процесса разработки.

Решение
---
Разработать макет текстового редактора, содержащего в себе главное меню установленного вида.

Задачи
---
- [x] - разработать макет согласно требованиям;
- [x] - макет согласован с членами команды.

Информация
---
Ссылка на ТТ
https://docs.google.com/document/d/10EriiF5dSBIvsouxwnN69tF3tUaq1Pcd/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true

Согласование
---
- [x] - @v01z 
- [x] - @Legendary2 
- [x] - @flagrans 
- [x] #11
- [x] - @MileX0k

**Comment by v01z** [comment]
Предложения правок [внёс в ТТ](https://docs.google.com/document/d/10EriiF5dSBIvsouxwnN69tF3tUaq1Pcd/edit).

**Comment by AJIKAIIIMMM** [comment]
Замечания исправлены. Требуется согласование.

**Comment by v01z** [comment]
+

**Comment by v01z** [comment]
Согласовано.

**Comment by Legendary2** [comment]
Согласовано

**Comment by MileX0k** [comment]
Согласовано

**Comment by vahabit84** [comment]
Согласовано

**Comment by flagrans** [comment]
Согласовано.

**Comment by v01z** [comment]
[Разработан макет приложения.](https://github.com/Legendary2/GB_CommandProgCPP_team3/tree/binary_cat/EditorTeam)

**Comment by flagrans** [comment]
Замечаний нет.

**Comment by flagrans** [comment]
Свернуть в функцию повторяющийся код в createActions()

**Comment by v01z** [comment]
> Свернуть в функцию повторяющийся код в createActions()

Код в методе createActions() сокращён[ за счёт добавления метода createAction()](https://github.com/Legendary2/GB_CommandProgCPP_team3/tree/binary_cat/EditorTeam).

**Comment by v01z** [comment]
Обнаружил в коде двойное создание объектов QString. Следует избавиться.

**Comment by v01z** [comment]
> Обнаружил в коде двойное создание объектов QString. Следует избавиться.

Исправил.

**Comment by v01z** [comment]
Макет приложения основан на ТТ[ (ссылка)](https://docs.google.com/document/d/10EriiF5dSBIvsouxwnN69tF3tUaq1Pcd/edit). Но в ТТ не была предусмотрена функция **"Align text center"**, которая [появилась в ТЗ](https://github.com/Legendary2/GB_CommandProgCPP_team3/issues/2#issuecomment-1410944694). Требуется внести соответствующие изменения в макет.

**Comment by flagrans** [comment]
Требуется внести изменения в макет согласно исправленному ТТ (в ТТ внес изменения).

**Comment by v01z** [comment]
> Требуется внести изменения в макет согласно исправленному ТТ (в ТТ внес изменения).

Необходимые изменения в макет внесены.

**Comment by flagrans** [comment]
Проверено, исправления приняты.

**Comment by Legendary2** [comment]
Исправления приняты

**Comment by v01z** [comment]
Произведено слияние ветки binary_cat c веткой develop. Задача выполнена.
