### ISSUE TITLE
R3B3[Bug] Баг в функции `Italic`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#100]
Проблема
---
Требуется исправить баг в функции `Italic`.
1. Функция не включается на пустом поле, без выделения.
2. Формат выделенного фрагмента текста определяется после курсора, не за ним.
3.  Функция не выключается при повторном ее вызове.

Решение
---
Устранить баги.

Задачи
---
- [x] - устранить баги;
- [x] - пройти тестирование.

Информация
---
При разработке функции следует использовать функционал разработанный @v01z:
[Функция](https://docs.google.com/document/d/1BYPuIvvvutrRO2XzGDRJJvAe-qMzU1G7/edit)

[Техническое требование](https://docs.google.com/document/d/1Xkft-j9SvvEfw4Jr4fi9Qb3VrFRnlrbX/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

**Comment by flagrans** [comment]
Проверил, можно лить.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
