### ISSUE TITLE
R3B5[Bug] Баг в функции `Crossed`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#102]
Проблема
---
Требуется исправить баг в функции `Crossed`.
1. Функция не включается на пустом поле, без выделения.
2. Формат выделенного фрагмента текста определяется после курсора, не за ним.
3.  Функция не выключается при повторном ее вызове.

Решение
---
Устранить баги.

Задачи
---
- [ ] - устранить баги;
- [ ] - пройти тестирование.

Информация
---
При разработке функции следует использовать функционал разработанный @v01z:
[Функция](https://docs.google.com/document/d/1BYPuIvvvutrRO2XzGDRJJvAe-qMzU1G7/edit)

[Техническое требование](https://docs.google.com/document/d/1SvrCH55qrpOCYEU8Nk8lNCM2Lz8FeasK/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

**Comment by Legendary2** [comment]
Сразу пройдусь по замечанию
3. Функция не выключается при повторном ее вызове.
 - функция включается и при повторном и при следующих ее вызовах, только на выделенном фрагменте текста. Так что замечание №3 не совсем корректно. По остальным - попытаюсь исправить.
В общем мое мнение - Формат выделенного фрагмента текста определяется после курсора, не за ним - исправить необходимо, исправлю. А по поводу первого замечания - по идее на пустом поле не должно ничего выделяться, НО - когда я перехожу на новую строку(абзац) и вызываю функцию Crossed - она не вызывается, нужно именно, что выделить текст. Если в именно в этом проблема - попытаюсь исправить.

**Comment by Legendary2** [comment]
UPDATE: Перепробовал множество вариантов аргументов функции. На данном этапе не получилось исправить недоработку кода, поскольку не нашел каких-либо нужных инструментов в Qt. QTextCursor - в данном случае принимает аргументы изменения QFont только на выделенный фрагмент. В QT для изменения форматирования текста используются как раз QTextCursor, QTextCharFormat (через который и меняется фон текста(а это именно что и есть ФОН) на зачеркнутый  crossedFormat.setFontStrikeOut(true или false);
Других классов для изменения форматирования текста в ходе исследований мною найдено не было. Нужно либо как-то по-другому произвести рефакторинг кода (полностью переделывать реализацию функции) через другие классы, методы и т.д., либо искать решение исправления. 
Также замечу, что функции Bold, Itallic, Crossed, Underlined - схожи по структуре кода, возможно решение кроется в том, что нужно данные функции объединять в единый блок - и там уже без использования цикла(или с использованием оных) прорабатывать общий функционал. 
В общем - на данном этапе я не нашел способа как это исправить.

**Comment by Legendary2** [comment]
UPDATE 1*: Увидел у @v01z вариант решения - Пытаюсь разобраться в его варианте решения проблемы.
Немного поработал - пока нет результатов, необходима помощь.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
