### ISSUE TITLE
R3B8[Bug] Баг в функции `Мультиязычность приложения`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#105]
Проблема
---
Требуется исправить баг в функции `Мультиязычность приложения`.
1. В приложении появились нелокализованные фрагменты, требуется актуализировать.

Решение
---
Устранить баги.

Задачи
---
- [x] - устранить баги;
- [ ] - пройти тестирование.

Информация
---
[Техническое требование](https://docs.google.com/document/d/14Pvf76idtlSPtum191TwimFQNYuTHofN/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

**Comment by v01z** [comment]
Локализация третьего релиза выполнена. 4c3ed59

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
