### ISSUE TITLE
R1D2[Doc]Разработка соглашения о кодировании для команды №3

### ISSUE THREAD

**Issue by flagrans** [Legendary2/GB_CommandProgCPP_team3#12]
##  Проблема
Требуется разработать соглашение о кодировании для команды №3.
## Решение
Разработать соглашение о кодировании, удовлетворяющее всем требованиям участников команды.
## Задачи
- [x] Перечислить все необходимые требования к оформлению кода;
- [x] Обсудить и согласовать требования;
- [x] Подготовить инструкцию по плагину QT Beautifier и clang-format (рассмотреть возможность использования через File);
- [x] Подготовить файл;
- [x] Проверить работу файла в IDE (несколько человек);
- [x] Залить на Git;
## Информация
Ссылка на инструкции и необходимые файлы:
https://docs.google.com/document/d/1wxdUi9BP23G8s934lm-9COrVExQ3GvGVHSxPixnaLLs/edit?usp=share_link

Согласование
- [x] @v01z
- [x] @Legendary2
- [x] @flagrans
- [x] @MileX0k
- [x] @AJIKAIIIMMM
- [x] @vahabit84
- [x] @FerKosNik

**Comment by AJIKAIIIMMM** [comment]
@flagrans 
Заголовок "Выработка Code style" лучше заменить на "Разработка соглашения о кодировании для команды №3".

Проблема
Требуется разработать соглашение о кодировании для команды №3.

Решение
Разработать соглашение о кодировании, удовлетворяющее всем требованиям участников команды.

Остальное все норм, можно разрабатывать инструкци.

**Comment by AJIKAIIIMMM** [comment]
Согласовано.

**Comment by flagrans** [comment]
Подготовил макет соглашения о кодировании
Подготовил инструкцию по плагину форматирования в Qt.
Требуется обсудить, дополнить, исправить.

**Comment by MileX0k** [comment]
Не знаю как вам, но лично мне совсем не удобно когда открывающая скобка пишется в той же строчке с функцией

**Comment by AJIKAIIIMMM** [comment]
Добавил комментарии к соглашению. @flagrans

**Comment by AJIKAIIIMMM** [comment]
> Не знаю как вам, но лично мне совсем не удобно когда открывающая скобка пишется в той же строчке с функцией

Предлагаю поднять данный вопрос на след мите @MileX0k .

**Comment by flagrans** [comment]
https://github.com/Legendary2/GB_CommandProgCPP_team3/issues/12#issuecomment-1417444005
Изменил согласно комментариям.

**Comment by flagrans** [comment]
На мите обговорили нюансы, добавил небольшую инструкцию и выложил файл .clang-format
https://drive.google.com/drive/folders/13-ntstCUdESmPX2pXuSUDy_4FOeyQ86S?usp=share_link
Большинством файл согласован, Перемещая в "Готово".

**Comment by AJIKAIIIMMM** [comment]
Соглашение о кодировании добавлено в вики проекта.
