### ISSUE TITLE
R3B9[Bug] Баг функции `Exit`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#122]
Проблема
---
Требуется исправить баг в функции `Exit`.
1. Функция не выполняет условия ТТ, а именно не вызывает диалоговое окно для сохранения текущего состояния текста, если изменения не были сохранены.

Решение
---
Устранить баги.

Задачи
---
- [x] - устранить баги;
- [x] - пройти тестирование.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1nAiqPR--NzGJDC99BleDBAeqTR7GV5A2/edit)

**Comment by MileX0k** [comment]
Залил для проверки
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/123

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
