### ISSUE TITLE
R1D3[Doc]Создание формы сдачи ДЗ

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#15]
Проблема
---
Требуется создать форму сдачи ДЗ для 2 урока

Решение
---
Создать форму, позволяющая унифицировать вид сдаваемого ДЗ участников команды

Задачи
---
- [x] - создать форму;
- [x] - согласовать с участниками;
- [x] - сдать ДЗ 2 урока.

Информация
---
Предварительный вариант формы ДЗ
https://docs.google.com/document/d/1eu0bX1yYBKI9jK1P_-AIhXK8ZAm7VIub/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true

Согласование
---
- [x] - @Legendary2 
- [x] - @flagrans 
- [x] - @FerKosNik 
- [x] - @MileX0k 
- [x] - @vahabit84 
- [x] - @v01z

**Comment by Legendary2** [comment]
согласовано
