### ISSUE TITLE
R1T1[Dev]Разработка функции `New` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#17]
Проблема
---
Требуется разработать функцию `New` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `New`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://drive.google.com/file/d/1kEhCCVR96gQvEmE3BgCzWa1yxQ8M0b0u/view)

Ревьювером данной функции является @MileX0k   .

**Comment by MileX0k** [comment]
Проверил работоспособность кода, свои функции выполняет. Готово к сливанию
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/32
