### ISSUE TITLE
R1T2[Dev]Разработка функции `Open` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#18]
Проблема
---
Требуется разработать функцию `Open` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Open`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции;

Информация
---
[Техническое требование](https://drive.google.com/file/d/1xhCRaR_GaZY5fABThsZcgNvf1n4zurAx/view)

Ревьювером данной функции является @MileX0k .

**Comment by Legendary2** [comment]
d199204 внес изменения в функцию onOpen()

**Comment by MileX0k** [comment]
Проверил работоспособность кода, свои функции выполняет. Готово к сливанию
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/32
