### ISSUE TITLE
R1T3[Dev]Разработка функции `Close` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#19]
Проблема
---
Требуется разработать функцию `Close` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Close`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции;

Информация
---
[Техническое требование](https://drive.google.com/file/d/1B2g0FNxPrragIvj6GYdW5-e8MARR0VEr/view)

Ревьювером данной функции является @Legendary2  .

**Comment by MileX0k** [comment]
Требуется проверка
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/28

**Comment by Legendary2** [comment]
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/28
Функция прошла ревьюинг. Свои функции выполняют, сделано даже больше (в частности реализовано окно предупреждения). На первый ран реализация годится. Багов, несоответствия ТТ не выявлено. Можно закрыть issue.

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.
