### ISSUE TITLE
R2D4[Doc]Разработка технического задания на текстовый редактор.  Команда №3

### ISSUE THREAD

**Issue by Legendary2** [Legendary2/GB_CommandProgCPP_team3#2]
Проблема
---
Требуется разработать техническое задание на текстовый редактор.

Решение
---
Разработать техническое задание, удовлетворяющее конечной цели проекта.

Задачи
---
- [x] - разработать техническое задание;
- [ ] - согласовать техническое задание с остальными членами команды.

Согласование
---
- [ ] - @v01z 
- [x] - @Legendary2 
- [ ] - @flagrans 
- [ ] - @FerKosNik 
- [x] - @MileX0k 
- [ ] - @vahabit84 

Предварительный вариант технического задания
https://docs.google.com/document/d/1hr4KDpOtBPyhKtTcPFCkK8MW4nARVoYz/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true

**Comment by AJIKAIIIMMM** [comment]
Разработана предварительная версия технического задания на текстовый редактор прошу ознакомиться.
https://docs.google.com/document/d/1hr4KDpOtBPyhKtTcPFCkK8MW4nARVoYz/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true

**Comment by Legendary2** [comment]
Предлагаю убрать "для закрытия курса" на первой странице ТЗ. Вообще где встречаются слова "для закрытия курса". Все-таки кодим ПО "по-настоящему". Внес небольшие правки по тексту(исправил опечатки).

**Comment by AJIKAIIIMMM** [comment]
> Предлагаю убрать "для закрытия курса" на первой странице ТЗ. Вообще где встречаются слова "для закрытия курса". Все-таки кодим ПО "по-настоящему". Внес небольшие правки по тексту(исправил опечатки).

Замечания исправлены.

**Comment by Legendary2** [comment]
Предварительно согласовано

**Comment by v01z** [comment]
[Требуется внести изменения в макет](https://github.com/Legendary2/GB_CommandProgCPP_team3/issues/10#issuecomment-1411502820) в соответствии с новыми требованиями.

**Comment by AJIKAIIIMMM** [comment]
В ТЗ добавлены новые функции (Tree Catalogues, Search through text, Search through tree catalogues, Open for read, Fonts, Text Colour, Highlight Text)

**Comment by AJIKAIIIMMM** [comment]
В ТЗ добавлены новые функции (Bold, Italic, Underlined, Crossed).

**Comment by AJIKAIIIMMM** [comment]
Документ разработан.
