### ISSUE TITLE
R1T4[Dev]Разработка функции `Exit` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#20]
Проблема
---
Требуется разработать функцию `Exit` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Exit`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции;

Информация
---
[Техническое требование](https://drive.google.com/file/d/1nAiqPR--NzGJDC99BleDBAeqTR7GV5A2/view)

Ревьювером данной функции является @Legendary2 .

**Comment by MileX0k** [comment]
Не знаю как вам, но лично мне совсем не удобно когда открывающая скобка пишется в той же строчке с функцией

**Comment by MileX0k** [comment]
Требуется проверка
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/28

**Comment by Legendary2** [comment]
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/28
Мой ревьюинг функции прошли. Они работают, выполняют возложенные функции. Ошибок в коде, а также несоответствия с ТТ я не заметил.

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.
