### ISSUE TITLE
R1T6[Dev]Разработка функции `Save As` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#22]
Проблема
---
Требуется разработать функцию `Save As` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Save As`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции;

Информация
---
[Техническое требование](url)

Ревьювером данной функции является @FerKosNik .

**Comment by v01z** [comment]
Разработана предварительная реализация функции SaveAs() f603b96a50adb6ac8ade04c5050b4c594000e02e

**Comment by v01z** [comment]
Освобождение выделенной в куче памяти под поле _file_ пока не было реализована. Поэтому передал контроль над _file_ под управление классу главного окна (_MainWindow_). ba5e6723264b39eed540b9a287dc3f12376e734c

**Comment by v01z** [comment]
Стиль кода  приведён в соответствие с соглашением о кодировании (комментарии изменил лишь в рамках текущего спринта). af21c170998d70907b7e74aeffa7c8a51798c0e3

**Comment by v01z** [comment]
Исправил ошибку, возникавшую в функции _SaveAs()_ при попытке перезаписи существующего файла. d051d15dea0c82e25f6ffd13ca5b49c8bc35e8fc

**Comment by FerKosNik** [comment]
В файле mainwindow.cpp в строчках 149 и 193 вывод сообщение "Не могу открыть файл", может должно быть "Не могу сохранить". Так же в первой случае сообщение на английском языке во втором на русском

**Comment by v01z** [comment]
> В файле mainwindow.cpp в строчках 149 и 193 вывод сообщение "Не могу открыть файл", может должно быть "Не могу сохранить". Так же в первой случае сообщение на английском языке во втором на русском

Исправлено. 5154741

**Comment by v01z** [comment]
Создан [pull request](https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/37).

**Comment by AJIKAIIIMMM** [comment]
Слияние ветки выполнено успешно.
