### ISSUE TITLE
R1T10[Dev]Разработка функции `Реализация мультиязычности приложения` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#23]
Проблема
---
Требуется разработать функцию `Реализация мультиязычности приложения` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Реализация мультиязычности приложения`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](url)

Ревьювером данной функции является @v01z .

**Comment by FerKosNik** [comment]
Разработана функция реализации мультиязычности (два языка), серьёзные изменения затронули мен: добавлен заголовочный файл с константными наименованиями пунктов меню const_string.h для их корректного изменения в соответствии активным языком меню.

**Comment by v01z** [comment]
Решение необходимо привести в соответствие со структурой проекта. Из системы контроля версий нужно удалить директорию '_debug_', а также следующие файлы: 
- ._qmake.stash_
- _EditorTeam.pro.user_
- _Makefile_
- _Makefile.Debug_
- _Makefile.Release_
- _resources.rcc_

В корневую директорию решения из вышестоящей ветки devel необходимо скопировать файлы:
- _.gitignore_
- _.gitattributes_ 
- _LICENSE_
- _README.MD_

В файле _README.MD_ нужно отразить описание текущей задачи.
В корне решения создать директорию EditorTeam и перенести туда следующие файлы:
- _EditorTeam.pro_
- _mainwindow.ui_
- _const_strings.h_
- _ui_mainwindow.h_
- _mainwindow.h_
- _mainwindow.cpp_
- _main.cpp_
- _l10n_ru.ts_
- _l10n_en.ts_
- _l10n_ru.qm_
- _l10n_en.qm_
- _resources.qrc_

**Comment by FerKosNik** [comment]
Оптимизировал структуру документов и добавил не достающие файлы в соответствии с замечаниями.

**Comment by v01z** [comment]
Проверено. Решение готво к слиянию с веткой _develop_.

**Comment by AJIKAIIIMMM** [comment]
Слияние проведено успешно.
