### ISSUE TITLE
R1T7[Dev]Разработка функции `Help` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#24]
Проблема
---
Требуется разработать функцию `Help` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Help`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции;
- [x]  - произведен рефакторинг кода.

Информация
---
[Техническое требование](url)

Ревьювером данной функции является @flagrans .

**Comment by AJIKAIIIMMM** [comment]
Ветка актуализирована с веткой develop. Можно продолжить разработку @lyashenko-an

**Comment by lyashenko-an** [comment]
Внес изменения по рекомендациям.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.

**Comment by AJIKAIIIMMM** [comment]
Требуется произвести рефакторинг данной функции, согласно условленных договоренностей на мите от 17.02. @lyashenko-an

**Comment by flagrans** [comment]
Обнаружена проблема - при закрытии окна основного приложения, не закрывается окно помощи если оно было открыто ранее.

**Comment by AJIKAIIIMMM** [comment]
Функция Help была залита в составе другой ветки.
