### ISSUE TITLE
R1T8[Dev]Разработка функции `About` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#25]
Проблема
---
Требуется разработать функцию `About` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `About`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] #74
- [x] - произведен рефакторинг кода.

Информация
---
[Техническое требование](url)

Ревьювером данной функции является @flagrans   .

**Comment by v01z** [comment]
@AJIKAIIIMMM, считаю целесообразным уже на этом этапе сделать возможность добавить изображение-логотип.

**Comment by lyashenko-an** [comment]
Ок

**Comment by lyashenko-an** [comment]
Добавил в "About" возможность добавить логотип, иконку логотипа вставил из что было в наличии.

**Comment by AJIKAIIIMMM** [comment]
Ветка актуализирована с веткой develop. Можно продолжить разработку @lyashenko-an

**Comment by flagrans** [comment]
1. в файле .pro отсутствует ui:
FORMS +=
должно быть:
FORMS += \
    mainwindow.ui
Так не компилируется.

2. Уже есть файл ресурсов, но 
RESOURCES += \
    resources/resources.qrc
RESOURCES = application.qrc
Тут получается переменной RESOURCES задается новое значение, а старое теряется, поэтому не работают темы приложения.
Если делать так, то через +=:
RESOURCES += \
    resources/resources.qrc
RESOURCES **+=** application.qrc
Необходимо использовать пока один файл:
RESOURCES += \
    resources/resources.qrc

3. Лишние (закомментированные строки кода) перед слиянием необходимо удалить.
  // msgBox.setTextFormat(Qt::RichText);
//   msgBox.setStandardButtons(QMessageBox::Ok);

4. В "About" убрать разработчиков, добавить название команды, и вставить лицензию Qt. Согласовано с тимлидом.

**Comment by flagrans** [comment]
Проверено.

**Comment by AJIKAIIIMMM** [comment]
Слияние выполнено успешно.

**Comment by AJIKAIIIMMM** [comment]
Требуется произвести рефакторинг кода функции, согласно условленным договоренностям на мите от 17.02. @lyashenko-an
