### ISSUE TITLE
R1T9[Dev]Разработка функции `Создание светлой и темной тем приложения` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#26]
Проблема
---
Требуется разработать функцию `Создание светлой и темной тем приложения` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Создание светлой и темной тем приложения`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](url)

Ревьювером данной функции является @vahabit84 .

**Comment by flagrans** [comment]
Разработка светлой и темной тем приложения - 6a19172a62557236adcfa2a71c26d18cd7f1212f
Требуется ревью.

Необходимо скопировать папку themes в папку с билдом приложения.

**Comment by AJIKAIIIMMM** [comment]
Требуется создать ресурсную папку с файлом формата .qrc для хранения и подтягивания тем к проекту. @flagrans

**Comment by flagrans** [comment]
Исправлено, темы запакованы в файл ресурсов, в связи с  этим внесены исправления в файл .pro - a92bc87e4333cf7a7b565b141a21f41f31ff351f
добавлено:
RESOURCES += \
    resources/resources.qrc

Требуется ревью.

**Comment by flagrans** [comment]
Создан pull request - https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/30

**Comment by AJIKAIIIMMM** [comment]
Слияние выполнено успешно.
