### ISSUE TITLE
R2D3[Doc] Архитектура ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#29]
Проблема
---
Требуется разработать архитектура ПО "Текстовый редактор".

Решение
---
Разработать архитектуру ПО, которая визуализирует взаимодействие классов внутри.

Задачи
---
- [ ] - разработать вариант архитектуры;
- [ ] - прогнать архитектуру через ревьюинг команды;
- [ ] - выкатить готовое решение.

Информация
---
Предварительный вариант архитектуры.
https://drive.google.com/file/d/1qS8htgRWCO_xbSD2LXnDbvvT3Ey58JNx/view?usp=sharing

Согласование
---
- [x] - @v01z 
- [x] - @Legendary2 
- [x] - @flagrans 
- [x] - @FerKosNik 
- [x] - @MileX0k 
- [x] - @vahabit84

**Comment by flagrans** [comment]
Необходимо поправить имена функций-членов например: вместо New() -> onNew(), Open() -> onOpen() и т. д.

**Comment by Legendary2** [comment]
Согласовано

**Comment by AJIKAIIIMMM** [comment]
Архитектура переработана. Предварительно добавлены несколько модулей и их взаимосвязь.
