### ISSUE TITLE
R2D1[Doc] Разработка набора иконок для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#31]
Проблема
---
Требуется разработать набор однотипных иконок.

Решение
---
Разработать набор однотипных иконок, не отличающихся стилистически друг от друга, для ПО "Текстовый редактор".

Задачи
---
- [x] - разработать предварительный набор иконок;
- [x] - согласовать с участниками команды.

Согласование
---
- [x] - @v01z 
- [x] - @Legendary2 
- [x] - @flagrans 
- [x] - @FerKosNik 
- [x] - @MileX0k 
- [x] - @vahabit84 
- [x] - @lyashenko-an 
- [x] - @AJIKAIIIMMM

**Comment by v01z** [comment]
Набор иконок разработан. Прошу согласовать, либо предложить изменения. [Ссылка на пак иконок.](https://drive.google.com/drive/folders/1VfB9YLNAdZaMWHNI9dfeY3VBIVtrYhu6)

**Comment by AJIKAIIIMMM** [comment]
К иконкам меню вопрос по разрешению, они не будет на интерфейсе пиксельно выглядить? И мейн иконку надо как-то доработать, на фоне иконок меню выглядит не очень, надо пофантазировать еще.  @v01z

**Comment by AJIKAIIIMMM** [comment]
Набор иконок разработан. @flagrans был назначен исполнителем для их имплементации в проект в рамках [Issue R2T15](https://github.com/Legendary2/GB_CommandProgCPP_team3/issues/65).

**Comment by AJIKAIIIMMM** [comment]
Требуется доразработка иконок для функций bold, italic, crossed, underlined. @v01z

**Comment by v01z** [comment]
Подготовил иконки bold, crossed, italic, underlined. cb101dc
![bold](https://user-images.githubusercontent.com/84637681/221246676-59d89472-4990-44ad-94f8-4dd3eb388498.png)
![crossed](https://user-images.githubusercontent.com/84637681/221246708-1af41350-c55e-484a-a338-f7398261ff7b.png)
![italic](https://user-images.githubusercontent.com/84637681/221246729-03268374-f760-460c-a89c-3442f36f3efa.png)
![underline](https://user-images.githubusercontent.com/84637681/221246754-22f0501d-7e51-47f3-8093-2ff7c2f5d135.png)
Прошу согласовать.
- [x] - @Legendary2 
- [ ] - @flagrans 
- [ ] - @FerKosNik 
- [ ] - @MileX0k 
- [ ] - @vahabit84 
- [ ] - @lyashenko-an 
- [ ] - @AJIKAIIIMMM

**Comment by AJIKAIIIMMM** [comment]
Иконку согласования не требует. Слияние выполнено.
