### ISSUE TITLE
R2D2[Doc] Разработка документа "Пользовательские истории"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#41]
Проблема
---
Требуется разработать документ "Пользовательские истории".

Решение
---
Разработать документ "Пользовательские истории", которые будет содержать в себе описание основных функций, с точки зрения конечного пользователя.

Задачи
---
- [x] - разработать документ;
- [x] - согласовать документ с остальными членами команды.

Согласование
---
- [x] - @v01z 
- [x] - @Legendary2 
- [x] - @flagrans 
- [x] - @FerKosNik 
- [x] - @MileX0k 
- [x] - @vahabit84 
- [x] - @lyashenko-an 

Предварительный вариант документа:
https://docs.google.com/spreadsheets/d/1ZAlRAmyAtYj41jMSkwJrqdNythfPlkgTog18RLdZIWY/edit?usp=share_link

**Comment by flagrans** [comment]
Подготовил [документ](https://docs.google.com/spreadsheets/d/1ZAlRAmyAtYj41jMSkwJrqdNythfPlkgTog18RLdZIWY/edit?usp=share_link), требуется согласование.

**Comment by AJIKAIIIMMM** [comment]
Добавил ID к рискам, и повестил номер спринта.
Согласовано, также после общего согласования прошу ишью не закрывать, т.к. документ будет дополняться. @flagrans

**Comment by Legendary2** [comment]
Мне все нравится, согласовано.

**Comment by AJIKAIIIMMM** [comment]
Документ разработан.
