### ISSUE TITLE
R2T2[Dev]Разработка функции `Copy text format` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#42]
Проблема
---
Требуется разработать функцию `Copy text format` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Copy text format`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1B880ze65Kni97ruSfYsypigszgU8eivw/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @flagrans .

**Comment by MileX0k** [comment]
Добавил реализацию согласно ТТ
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/76

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
