### ISSUE TITLE
R2T3[Dev]Разработка функции `Align text right` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#43]
Проблема
---
Требуется разработать функцию `Align text right` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Align text right`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1TGXq6NcXGGgsJKx8WcVerC16lVV20X_p/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @Legendary2 .

**Comment by t3rmin4lrus** [comment]
Сегодня гляну

**Comment by Legendary2** [comment]
Функцию протестировал, все работает. Никаких нареканий. Можно завершать.

**Comment by Legendary2** [comment]
Проверил работоспособность функции [Align text right]. Все работает и соответствует ТТ. Каких-либо замечаний нет.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
