### ISSUE TITLE
R2T4[Dev]Разработка функции `Align text left` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#44]
Проблема
---
Требуется разработать функцию `Align text left` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Align text left`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1MYbVD3PtjAF1NulKByjk1Pc9x9_x5w26/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @Legendary2 .

**Comment by Legendary2** [comment]
@lyashenko-an Проверил работоспособность функции [Align text left]. Все работает и соответствует ТТ. Каких-либо замечаний нет.

**Comment by lyashenko-an** [comment]
функция проверена

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
