### ISSUE TITLE
R2T5[Dev]Разработка функции `Align text center` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#45]
Проблема
---
Требуется разработать функцию `Align text center` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Align text center`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1CjwkA9xok7YhL36HgR1fNU4b_WJrBvAh/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @FerKosNik .

**Comment by Legendary2** [comment]
Разработал функцию выравнивания текста по центру.

**Comment by FerKosNik** [comment]
Проверил, функция работает.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
