### ISSUE TITLE
R2T6[Dev]Разработка функции `Fonts` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#46]
Проблема
---
Требуется разработать функцию `Fonts` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Fonts`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1xRLsZM_a2uBuvAAeEKcGcTJ-nZwHmdsq/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @v01z .

**Comment by vahabit84** [comment]
Принял

**Comment by vahabit84** [comment]
Формат txt не сохраняет форматирование текста......

**Comment by AJIKAIIIMMM** [comment]
Это ожидаемо. Если все сделал, создавай Pull request. @vahabit84

**Comment by v01z** [comment]
Согласно [ТТ к функции](https://docs.google.com/document/d/1xRLsZM_a2uBuvAAeEKcGcTJ-nZwHmdsq/edit), изменение шрифта должно применятся не ко всему тексту, а только к выделенному фрагменту. Также требуется удалить следующие файлы:
- _mainwindow.cpp_ из корня проекта;
- _EditorTeam.pro.user_ из директории исходников.

**Comment by v01z** [comment]
Проверено, замечаний нет.

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.
