### ISSUE TITLE
R2T7[Dev]Разработка функции `Key bindings` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#47]
Проблема
---
Требуется разработать функцию `Key bindings` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Key bindings`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1Ywb3iePv5B76JftcIQ1hTqQAPQWeW-WB/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @vahabit84.

**Comment by FerKosNik** [comment]
Сделал статичные горячие клавиши.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
