### ISSUE TITLE
R2T1[Dev]Разработка функции `Print` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#48]
Проблема
---
Требуется разработать функцию `Print` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Print`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1xSB2hLa-fw5cAJQIeYQidGwXLOxEo6s0/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @flagrans .

**Comment by MileX0k** [comment]
Добавил реализацию печатанья документа согласно ТТ
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/75

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
