### ISSUE TITLE
R3T3[Dev]Разработка функции `Tree catalogues` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#51]
Проблема
---
Требуется разработать функцию `Tree catalogues` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Tree catalogues`, в соответствии ТТ.

Задачи
---
- [ ] - разработать функцию согласно ТТ;
- [ ] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1x4YnrRcL7s_qXcoh8-laScy80gpi793H/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @lyashenko-an .

**Comment by Legendary2** [comment]
@lyashenko-an @AJIKAIIIMMM @Legendary2 @flagrans @FerKosNik @cyberhoffman @v01z 
При проработке функции возникли проблемы.
В общем бросаю на обсуждение пример того, как должна выглядеть функция в итоге (нашел на просторах интернета на форуме: https://www.programmersought.com/article/62437112218/). Я так понимаю ,что именно это и требуется:
![1231232](https://user-images.githubusercontent.com/747806/223087354-39b18ebd-ec7d-48a0-a8dd-fe837b8ce925.png)

**Comment by Legendary2** [comment]
@lyashenko-an @AJIKAIIIMMM @Legendary2 @flagrans @FerKosNik @cyberhoffman @v01z 
Проблемы такие: 
1. Пока не нашел решения по отображению пути файла - даже хотя бы в нижнем левом углу(как на скриншоте выше).
2. Общая проблема (более глобальная) - когда файл открыт внутри окна программы, в нем как раз таки отображается путь открытого файла. Но так как у нас в данный момент не реализовано многооконность приложения(MDI) - то не вижу смысла разрабатывать функцию Tree catalogues или по крайней мере - отображение в окне документа, если это возможно.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
