### ISSUE TITLE
R3T5[Dev]Разработка функции `Text colour` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#53]
Проблема
---
Требуется разработать функцию `Text colour` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Text colour`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
При разработке функции следует использовать функционал разработанный @v01z:
[Функция](https://docs.google.com/document/d/1BYPuIvvvutrRO2XzGDRJJvAe-qMzU1G7/edit)

[Техническое требование](https://docs.google.com/document/d/1aUzgEJNIMKCSBsG8EbmmAsE8XTSnQgdj/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @FerKosNik .

**Comment by MileX0k** [comment]
Добавил функцию, требуется проверка
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/117

**Comment by v01z** [comment]
Тестирование завершено успешно.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
