### ISSUE TITLE
R3T6[Dev]Разработка функции `Highlight Text` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#54]
Проблема
---
Требуется разработать функцию `Highlight Text` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Highlight Text`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
При разработке функции следует использовать функционал разработанный @v01z:
[Функция](https://docs.google.com/document/d/1BYPuIvvvutrRO2XzGDRJJvAe-qMzU1G7/edit)

[Техническое требование](https://docs.google.com/document/d/1iUnYqCDctw8sc23MbE9aO9NswXSFs8fZ/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

[Пример реализации](https://itnotesblog.ru/note/qsyntaxhighlighter-podsvetka-sintaksisa-v-qt)

Ревьювером данной функции является @FerKosNik .

**Comment by MileX0k** [comment]
Разработал функцию согласно ТТ
https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/119

**Comment by v01z** [comment]
Функция протестирована, замечания [приведены по ссылке](https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/119#issuecomment-1465284717).

**Comment by v01z** [comment]
Тестирование завершено успешно.

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
