### ISSUE TITLE
R2T10[Dev]Разработка `модуля работы с файлами`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#55]
Проблема
---
Требуется разработать `модуль работы с файлами` для ПО "Текстовый редактор"

Решение
---
Разработать функцию  `модуль работы с файлами`, в соответствии ТТ.

Задачи
---
- [x] - разработать `модуль работы с файлами` согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1uOb4L7-NNU30559hk20OG2Nzwg_QCDSx/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @flagrans .

**Comment by v01z** [comment]
Для устранения жёсткой привязки кода к исключительно одному типу хранения данных был создан абстрактный класс _IDevHandler_, наследник которого, имплементируя чисто виртуальные функции своего родителя, способен обеспечить работу с обьектами разных выбранных типов. В данном конкретном решении класс-потомок _FileHandler_ использует в качестве объекта хранения тип _QFile_.  01f7306

**Comment by flagrans** [comment]
Думаю необходимо добавить в "Title " у названия файла признак сохранения изменений в виде "*"

**Comment by v01z** [comment]
> Думаю необходимо добавить в "Title " у названия файла признак сохранения изменений в виде "*"

Замечание учтено в коммите 4a68a00

**Comment by flagrans** [comment]
1. Звездочка появляется только после второго введенного символа (либо после второго нажатия Enter и т.д.)
2. Сохранять дает без расширения, а вот открыть не дает (не видит файлы без расширения).

**Comment by v01z** [comment]
> 1. Звездочка появляется только после второго введенного символа (либо после второго нажатия Enter и т.д.)
> 
>     2. Сохранять дает без расширения, а вот открыть не дает (не видит файлы без расширения).

Исправлено. d0a82a2

**Comment by AJIKAIIIMMM** [comment]
Слияние выполнено успешно.
