### ISSUE TITLE
R3T8[Dev]Разработка диалогового окна `Settings`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#56]
Проблема
---
Требуется разработать диалоговое окно `Settings` для ПО "Текстовый редактор"

Решение
---
Разработать  диалоговое окно `Settings`, в соответствии ТТ.

Задачи
---
- [x] - разработать  диалоговое окно `Settings` согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1Wsx_fDnIdu5WTesue6_8dyB6ahufUJwk/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @flagrans .

**Comment by v01z** [comment]
Диалоговое окно настроек разработано. 132d753

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
