### ISSUE TITLE
R2T8[Dev]Имплементация системы сборки проекта `CMake` в проект команды № 3

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#57]
Проблема
---
Требуется имплементировать систему сборки проекта `CMake` в проект команды № 3.

Решение
---
Имплементировать систему сборки проекта `CMake` в проект команды № 3, для подгрузки необходимых ресурсных файлов в автоматическом режиме.

Задачи
---
- [x] - имплементировать систему сборки проекта;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](url)

[CMake информация](https://radioprog.ru/post/1571)

Ревьювером данной функции является @flagrans .

**Comment by v01z** [comment]
Решение готово. 440d1d8
Для исполнения задачи пришлось сделать рефакторинг класса _HelpBrowser_, так как обьявление и реализация последнего располагались в одном файле и без ограничения количества включений при сборке (например, **#pragma once**).
![Снимок экрана_2023-02-14_22-14-56](https://user-images.githubusercontent.com/84637681/218839877-161a3197-4d7f-4eeb-9ee4-730ee6e62e3b.png)

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.
