### ISSUE TITLE
R3T9[Dev] Имплементация собственного расширения для работы ПО

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#59]
Проблема
---
Требуется разработать и имплементировать собственное расширение для ПО "Текстовый редактор"

Решение
---
Разработать  и имплементировать собственное расширение файла, для работы с форматированием текста.

Задачи
---
- [x] - разработать формат;
- [x]  - имплементировать формат в ПО;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1YCXdayApfr3uAHVTyZ_mVKy6xSWl68v1/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @v01z .

https://docs.google.com/document/d/1TfkZAY0g66JK6aiAeHP5nfrTnXCV0AcwD97BLVUnlNw/edit

**Comment by Legendary2** [comment]
Командой было принято решение по поводу  упрощения разработки на данном этапе с помощью написания собственного расширения файлов.
@flagrans Андрей предложил собственный вариант, показал свое видение, поскольку на него была возложена такая задача по окончанию одного из Scrum. . Был спор, по окончанию которого я понял, что это действительно хорошая идея на данном этапе. С моей стороны - поддерживаю создание нового расширения, вариант Андрея любопытен. В общем с моей стороны даю зеленый свет.

**Comment by v01z** [comment]
Ссылка на "Техническое требование" не рабочая. Также не указан/ы ревьювер/ревьюверы. На scrum'е во время презентации предварительного видения работы перспективного расширения был показан код с задействованием POSIX-функции _system()_. Учитывая, что наш проект основан на фреймворке Qt, более логичным будет использовать [_QProcess_](https://doc.qt.io/qt-6.2/qprocess.html).

**Comment by flagrans** [comment]
[Примерное описание.](https://docs.google.com/document/d/1TfkZAY0g66JK6aiAeHP5nfrTnXCV0AcwD97BLVUnlNw/edit?usp=share_link)

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
