### ISSUE TITLE
R2T14[Dev]Разработка функции `Crossed` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#64]
Проблема
---
Требуется разработать функцию `Crossed` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Crossed`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [ ] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1SvrCH55qrpOCYEU8Nk8lNCM2Lz8FeasK/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является.

**Comment by Legendary2** [comment]
Функцию реализовал. Прошу назначить ревьюера
