### ISSUE TITLE
R2T15[Dev]Разработка функции `ToolBar` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#65]
Проблема
---
Требуется разработать функцию `ToolBar` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `ToolBar`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1SzPooaHwk8TNLR42xm7-YmXXB9HP0FIS/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @v01z .

**Comment by v01z** [comment]
Необходимо добавить (прописать в заголовочном файле _const_strings.h_, файле реализации _mainwindow.cpp_ и файле ресурсов _resources/resources.qrc_) иконку **paste_format.png** (сам же файл изображения _paste_format.png_ в директории _resources/images/_ имеется).

**Comment by flagrans** [comment]
Переделал, логичнее создавать в функции, чтобы был порядок следования вне зависимости от порядка в других функциях.

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.

**Comment by AJIKAIIIMMM** [comment]
Требуется на панель инструментов добавить функции bold, underlined, italic, crossed. @flagrans

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
