### ISSUE TITLE
R2T16[Dev]Разработка функции `Размер шрифта` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#66]
Проблема
---
Требуется разработать функцию `Размер шрифта` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Размер шрифта`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1CuG4j4alYJfxOf_iT3LJoMIxufX_O_PH/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @lyashenko-an

**Comment by v01z** [comment]
Задача реализована [в соответствии с ТТ](https://docs.google.com/document/d/1CuG4j4alYJfxOf_iT3LJoMIxufX_O_PH/edit). eeb9178 2a012c7

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.
