### ISSUE TITLE
R2T17[Dev]Разработка функции `Apply text format` для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#73]
Проблема
---
Требуется разработать функцию `Apply text format` для ПО "Текстовый редактор"

Решение
---
Разработать функцию `Apply text format`, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1925OKHeCbkk3ngoDdNOLzDWcRkiGqdz4/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является.

**Comment by v01z** [comment]
Решение подготовлено для проверки. 801d009

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
