### ISSUE TITLE
R2T18[Dev] Разработка контекстного меню для ПО "Текстовый редактор"

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#84]
Проблема
---
Требуется разработать контекстное меню для ПО "Текстовый редактор"

Решение
---
Разработать контекстное меню, в соответствии ТТ.

Задачи
---
- [x] - разработать функцию согласно ТТ;
- [x] - пройти ревьювинг функции.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1xHIrcEJKTR9grVI12ggvOyb82ahdaTPd/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

Ревьювером данной функции является @lyashenko-an .

**Comment by v01z** [comment]
Контекстное меню разработано. 497d26a

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
