### ISSUE TITLE
R3B1[Bug] Унификация функций форматирования текста

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#94]
Проблема
---
Требуется унифицировать работу функций форматирования.

Решение
---
Разработать общую функцию, которая будет вызываться всеми функциями форматирования.

Задачи
---
- [x] - функция разработана.
- [x] - функция протестирована.

Информация
---
Ревьювером является @flagrans .

**Comment by v01z** [comment]
Функция разработана. a5c4bfa
Подробное описание работы  -[ ссылка на документ](https://docs.google.com/document/d/1BYPuIvvvutrRO2XzGDRJJvAe-qMzU1G7/edit).

**Comment by AJIKAIIIMMM** [comment]
Слияние произведено успешно.

**Comment by v01z** [comment]
Произведён рефакторинг для обеспечения возможности работы со всем функциями, связанными с форматированием текста. 6b4d909

**Comment by v01z** [comment]
В целях уменьшения объёма кода функция fontFeaturesEquals() изменена. 6bf504c

**Comment by AJIKAIIIMMM** [comment]
Слияние прошло успешно.
