### ISSUE TITLE
R3B2[Bug] Баг в функции `Change style`

### ISSUE THREAD

**Issue by AJIKAIIIMMM** [Legendary2/GB_CommandProgCPP_team3#97]
Проблема
---
При смене темы ПО на светлую в системе с темной темой, происходит подстройка под параметры ОС

Решение
---
Найти решение данное проблемы

Задачи
---
- [x] - ПО остается в светлой теме даже если системная тема темная.

Информация
---
[Техническое требование](https://docs.google.com/document/d/1nOE652ngDr_JAAamAwu0H0ilNKHDCNsN/edit?usp=share_link&ouid=108708398095368132802&rtpof=true&sd=true)

**Comment by v01z** [comment]
[Следует закрыть без слияния.](https://github.com/Legendary2/GB_CommandProgCPP_team3/pull/98#issuecomment-1455061489)
